[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.0",
    "mcp[cli]>=1.10.1",
    "openai>=1.93.3",
    "python-dotenv>=1.1.1",
]
